build: bring back configure warning when pkg.m4 is absent
Commit 24b1513296fd61722166625ad46be1c56a5efc44 removed the warning
when the configure script is generated without pkg.m4. I added that
warning years ago (see 103f1a497a9ebbcab021c1a8d21276802d1922c6) to
prevent downstream distributions from creating a tarball with an
"incomplete" configure script. Add the warning back, reword the
messages to tell exactly what feature would be missing (to builders),
and also add FORCE_MAKE_DIST variable for builders who want to ignore
the warning. :)

Signed-off-by: Kang-Che Sung <explorer09@gmail.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -508,8 +508,9 @@ cppcheck:
 	cppcheck -q -v . --enable=all -DHAVE_OPENVZ
 
 dist-hook: $(top_distdir)/configure
-	@if grep 'pkg_m4_absent' '$(top_distdir)/configure'; then \
-	   echo 'ERROR: configure is generated without pkg.m4. Please supply pkg.m4 and run ./autogen.sh to rebuild the configure script.'>&2; \
+	@if test "x$$FORCE_MAKE_DIST" = x && \
+	   grep 'pkg_m4_absent' '$(top_distdir)/configure' >/dev/null; then \
+	   echo 'ERROR: This distribution would have incomplete pkg-config support. Rebuilding the configure script is advised. Set FORCE_MAKE_DIST=1 to ignore this warning.'>&2; \
 	   (exit 1); \
 	else :; \
 	fi
